# DIY Numpad - ZMK Config
# Board: Pro Micro NRF52840 (nice!nano v2 compatible)

# Bluetooth
CONFIG_ZMK_BLE=y
CONFIG_BT_DEVICE_NAME="Min Numpad"
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n

# USB (vừa BLE vừa USB cùng lúc)
CONFIG_ZMK_USB=y

# Sleep / Power saving
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=300000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1080000

# Enable NFC pins (P0.09, P0.10) as normal GPIO (needed for D10/D16)
CONFIG_NFCT_PINS_AS_GPIOS=y

# WS2812B underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=n
